spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare1?createDatabaseIfNotExist=true&autoReconnect=true
    username: ${dbusername}
    password: ${dbpassword}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

